// admin-frontend/src/views/farming-behavior/index.vue
<template>
  <div class="farming-behavior-container">
    <el-card shadow="hover">
      <template #header>
        <div class="card-header">
          <span>农事实践打卡反馈</span>
          <el-button type="primary" size="small" @click="fetchData">刷新数据</el-button>
        </div>
      </template>

      <el-table :data="tableData" style="width: 100%" v-loading="loading">
        <el-table-column prop="record_id" label="记录ID" width="100" />
        <el-table-column prop="user_name" label="农户姓名" width="120" />
        <el-table-column prop="township" label="所属乡镇" width="150" />
        <el-table-column prop="crop_type" label="作物类型" width="120" />
        <el-table-column prop="farming_stage" label="生长阶段" width="120" />
        <el-table-column prop="reminder_category" label="提醒类别" />
        <el-table-column prop="record_time" label="打卡时间" width="180" />
        <el-table-column prop="is_adopted_advice" label="建议采纳状态" width="120">
          <template #default="scope">
            <el-tag :type="scope.row.is_adopted_advice ? 'success' : 'info'">
              {{ scope.row.is_adopted_advice ? '已采纳' : '未采纳' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="120" fixed="right">
          <template #default="scope">
            <el-button 
              v-if="!scope.row.is_adopted_advice" 
              size="small" 
              type="success" 
              @click="handleAdopt(scope.row)">
              标记为采纳
            </el-button>
          </template>
        </el-table-column>
      </el-table>
      
      <div class="pagination-container">
        <el-pagination
          background
          layout="total, prev, pager, next"
          :total="total"
          v-model:current-page="currentPage"
          :page-size="pageSize"
          @current-change="handlePageChange"
          class="mt-4"
        />
      </div>
    </el-card>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import axios from 'axios'

const loading = ref(false)
const tableData = ref([])
const total = ref(0)
const currentPage = ref(1)
const pageSize = ref(20)

const fetchData = async () => {
  loading.value = true
  try {
    const res = await axios.get('/admin/farming-behavior', {
      params: {
        skip: (currentPage.value - 1) * pageSize.value,
        limit: pageSize.value
      }
    })
    tableData.value = res.data.data
    total.value = res.data.total
  } catch (error) {
    ElMessage.error('加载农事记录失败')
    console.error(error)
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  fetchData()
})

const handlePageChange = (page) => {
  currentPage.value = page
  fetchData()
}

const handleAdopt = async (row) => {
  try {
    await ElMessageBox.confirm(`确认将 ${row.user_name} 的此条记录标记为已采纳此建议吗？`, '采纳确认', { confirmButtonText: '确定', cancelButtonText: '取消', type: 'success' })
    
    await axios.post(`/admin/farming-behavior/${row.record_id}/adopt`, {
      is_adopted: true
    })
    
    row.is_adopted_advice = true
    ElMessage({ type: 'success', message: '已成功标记为采纳' })
  } catch (err) {
    if (err !== 'cancel') {
        ElMessage.error('操作失败')
    }
  }
}
</script>

<style scoped>
.farming-behavior-container {
  width: 100%;
}
.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.pagination-container {
  margin-top: 20px;
  display: flex;
  justify-content: flex-end;
}
</style>

// Web-frontend/src/pages/admin/FarmingBehavior.jsx
import { useEffect, useState } from 'react';
import axios from 'axios';

const API_BASE_URL = 'http://127.0.0.1:8000/api';

export default function FarmingBehavior() {
    const [tableData, setTableData] = useState([]);
    const [loading, setLoading] = useState(false);

    const fetchData = async () => {
        setLoading(true);
        try {
            const token = localStorage.getItem('token');
            const res = await axios.get(`${API_BASE_URL}/admin/farming-behavior`, {
                headers: { Authorization: `Bearer ${token}` }
            });
            setTableData(res.data.data || []);
        } catch (error) {
            console.error('加载农事记录失败', error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => { fetchData(); }, []);

    const handleAdopt = async (record_id) => {
        if (!window.confirm('确认将此条记录标记为已采纳此建议吗？')) return;
        try {
            const token = localStorage.getItem('token');
            await axios.post(`${API_BASE_URL}/admin/farming-behavior/${record_id}/adopt`,
                { is_adopted: true },
                { headers: { Authorization: `Bearer ${token}` } }
            );
            fetchData();
        } catch (err) {
            alert('操作失败');
        }
    };

    return (
        <div className="table-container glass-panel delay-100">
            <div className="tab-header-actions" style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '15px' }}>
                <h3 style={{ margin: 0, fontWeight: 600 }}>农事实践打卡反馈</h3>
                <button className="btn-approve" onClick={fetchData} style={{ padding: '6px 12px' }}>刷新数据</button>
            </div>
            <table className="admin-table">
                <thead>
                    <tr>
                        <th>记录ID</th>
                        <th>农户姓名</th>
                        <th>所属乡镇</th>
                        <th>作物类型</th>
                        <th>生长阶段</th>
                        <th>提醒类别</th>
                        <th>状态</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {loading ? <tr><td colSpan="8" style={{ textAlign: 'center', padding: '20px' }}>加载中...</td></tr> :
                        tableData.length === 0 ? <tr><td colSpan="8" style={{ textAlign: 'center', padding: '20px' }}>暂无记录</td></tr> :
                            tableData.map(row => (
                                <tr key={row.record_id}>
                                    <td>{row.record_id}</td>
                                    <td>{row.user_name}</td>
                                    <td>{row.township}</td>
                                    <td>{row.crop_type}</td>
                                    <td>{row.farming_stage}</td>
                                    <td>{row.reminder_category}</td>
                                    <td>
                                        <span className={`status-badge ${row.is_adopted_advice ? 'status-1' : 'status-0'}`}>
                                            {row.is_adopted_advice ? '已采纳' : '未采纳'}
                                        </span>
                                    </td>
                                    <td>
                                        {!row.is_adopted_advice && (
                                            <button className="btn-approve" onClick={() => handleAdopt(row.record_id)}>标记为采纳</button>
                                        )}
                                    </td>
                                </tr>
                            ))}
                </tbody>
            </table>
        </div>
    );
}
